name: "IndexNow"

on:
  workflow_dispatch:  # Allows you to run this workflow manually from the Actions tab

permissions:
  contents: write
  actions: write
  secrets: write  # Ensure the token has write permissions to secrets

jobs:
  check-and-submit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install GitHub CLI
      run: |
        type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
        && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
        && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
        && sudo apt update \
        && sudo apt install gh -y

    - name: Authenticate GitHub CLI
      run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    - name: Check if IndexNow key exists
      id: check-key
      run: |
        if gh secret list | grep -q 'INDEXNOW_KEY'; then
          echo "EXISTS=true" >> $GITHUB_ENV
        else
          echo "EXISTS=false" >> $GITHUB_ENV
        fi

    - name: Generate IndexNow key if not exists
      id: generate-key
      if: env.EXISTS == 'false'
      run: |
        GENERATED_KEY=$(python generateKey.py)
        echo "GENERATED_INDEXNOW_KEY=${GENERATED_KEY}" >> $GITHUB_ENV
        echo "${GENERATED_KEY}" > indexnow_key.txt

    - name: Save IndexNow key to GitHub secrets
      if: env.EXISTS == 'false'
      run: |
        gh secret set INDEXNOW_KEY --body "${{ env.GENERATED_INDEXNOW_KEY }}"

    - name: Read IndexNow key from secret
      if: env.EXISTS == 'true'
      run: echo "INDEXNOW_KEY=${{ secrets.INDEXNOW_KEY }}" >> $GITHUB_ENV

    - name: IndexNow action
      uses: bojieyang/indexnow-action@v2
      with:
        sitemap-location: "https://feelingchart.heytcm.com/sitemap.xml"
        since: 1
        since-unit: "day"
        key: ${{ env.INDEXNOW_KEY }}

    - name: Commit and push if key changed
      if: env.EXISTS == 'false'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add indexnow_key.txt
        git commit -m "Update IndexNow key" || echo "No changes to commit"
        git push
