name: "IndexNow"

on:
  workflow_dispatch:  # Allows you to run this workflow manually from the Actions tab

permissions:
  contents: write
  actions: write
  secrets: write  # Ensure the token has write permissions to secrets

jobs:
  check-and-submit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install GitHub CLI
      run: sudo apt-get install -y gh

    - name: Authenticate GitHub CLI
      run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    - name: Check if IndexNow key exists
      id: check-key
      run: |
        if gh secret list | grep -q 'INDEXNOW_KEY'; then
          echo "INDEXNOW_KEY exists"
          echo "EXISTS=true" >> $GITHUB_ENV
        else
          echo "INDEXNOW_KEY does not exist"
          echo "EXISTS=false" >> $GITHUB_ENV
        fi

    - name: Generate IndexNow key if not exists
      if: env.EXISTS == 'false'
      run: |
        GENERATED_INDEXNOW_KEY=$(python generateKey.py)
        echo "GENERATED_INDEXNOW_KEY=$GENERATED_INDEXNOW_KEY" >> $GITHUB_ENV
        echo $GENERATED_INDEXNOW_KEY > indexnow_key.txt

    - name: Save IndexNow key to GitHub secrets
      if: env.EXISTS == 'false'
      run: |
        gh secret set INDEXNOW_KEY --body "$GENERATED_INDEXNOW_KEY"

    - name: Read IndexNow key from secret
      if: env.EXISTS == 'true'
      run: echo "INDEXNOW_KEY=${{ secrets.INDEXNOW_KEY }}" >> $GITHUB_ENV

    - name: IndexNow action
      uses: bojieyang/indexnow-action@v2
      with:
        sitemap-location: "https://feelingchart.heytcm.com/sitemap.xml"
        since: 1
        since-unit: "day"
        key: ${{ env.INDEXNOW_KEY }}
